# Generated by Django 5.1 on 2024-08-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='judgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_of_judgment', models.CharField(max_length=20)),
                ('Conclusion_of_judgment', models.CharField(max_length=20)),
                ('Facts_of_judgment', models.CharField(max_length=20)),
                ('case_laws_that_apply', models.CharField(max_length=20)),
                ('Reasoning_for_selection', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'judgment',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('uemail', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'UserInfo',
            },
        ),
    ]
