# Generated by Django 5.1 on 2024-08-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document_Processing', '0002_user_delete_judgment_delete_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Upload_Document', models.FileField(blank=True, upload_to='Documents/')),
            ],
        ),
    ]
