# Generated by Django 5.1 on 2024-08-27 07:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document_Processing', '0003_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='Title',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
