# Generated by Django 5.1 on 2024-08-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document_Processing', '0004_document_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='Upload_Document',
            field=models.ImageField(blank=True, upload_to='Documents/'),
        ),
    ]
